services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: api-gateway
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    command: ["node dist/apps/api-gateway/main.js"]

  deliveries-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: deliveries-service
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    command: ["node dist/apps/deliveries-service/main.js"]

  listings-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: listings-service
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
    command: ["node dist/apps/listings-service/main.js"]

  orders-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: orders-service
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production
    command: ["node dist/apps/orders-service/main.js"]

  users-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: users-service
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=production
    command: ["node dist/apps/users-service/main.js"]
